### ISSUE TITLE
Refactor into multiple sub packages

### ISSUE THREAD

**Issue by MoMannn** [smart-on-fhir/health-cards-dev-tools#162] opened 2021-10-04 08:17 UTC
There are multiple functionalities included in this package that are not dependant on each other and could be standalone sub packages based on dev needs. For example reading qr code image ca be completely standalone etc. Maybe a better way would be to do a lib with the basic functionality (actually verifying) and this repo uses that lib with additional functionalities it provides.

**Comment by christianpaquin** [comment] 2021-10-04 19:18
As I commented on issue #161, the explicit goal of the project, as stated in the README, is to provide an implementation validation tool, vs. a library that can be used to validate SMART Health Cards directly. Our tool implements some validation paths that shouldn't be part of a real-life card validator, to help developers debug their issuance implementations. The current packaging discourages, by design, "blind" copy-paste into other projects. Developers are welcome to copy code and patterns from our project, but should do so with care, keeping their threat model in mind.

**Comment by christianpaquin** [comment] 2021-10-15 20:52
I'll close this issue for now. Feel free to provide more suggestions in the discussion forum.

**Closed by christianpaquin** 2021-10-15 20:52 UTC
