### ISSUE TITLE
QR numeric validation fails while using package as npm module in firebase project

### ISSUE THREAD

**Issue by rajeshmbg3vvdntech** [smart-on-fhir/health-cards-dev-tools#160] opened 2021-09-27 10:51 UTC
Error Log : 
data : shc:/5676290952432060346029243740446031222959532654603460292540772804336028702864716745222809286155305564710341432164324111083963210645240371337721263863367742423708412663394539292955640442562759653725333844612060573601044529335375327524285350225968720008030539575742256839640328213022662868211155057058455069267773606139525011083264624268223104740764451045630950111177703644402033393675716827345410356926565730386000081176316166640376776930710906357267366036582504736622096504567560416209303066265636100527722670630428005067442959356152380940583043663806770856403160587757736365656130647000682937564370680765541240684063102130583275292675433965106904551162614255660376650042356721342342554562454266370950436537405210561021760020097700437644210034585639442365226533526612341124355020081037344134097456734043427069747240276011655923126034046035384544452066406077226033566523690559503024717271096041095744387370675552740569200671443036530861245272587329773403682930680632445972386224566975253835776306372345312661255623347125672638533208317026332474552606206363717457354437566033295934071134255257372508737405290959084022316550401140742067764275407726254523207205750074357423420943083736575338281139273054555007366664524360612259372542647538392532385658434175034560031221711057411233765866007112217365233903604132526174123256592068714566370657655706702959507204693435767756433312573142087224551068535074680421763365376162571165733130046635045074000430400850502623752434747611013453005959216957543333074044436150543426432525114567454553295810086252675570714303746729422959347220561100533956535558082141087056327555092162005545654375097342236239066836 -- **console log of File Data** 
>  Error: Command failed: /usr/local/bin/firebase ./node_modules/health-cards-dev-tools/js/src/shc-validator.js --path  /var/projects/qrSDKDemo/health-cards-dev-tools/qrnumeric.txt --type qrnumeric
>  pkg/prelude/bootstrap.js:1359
>        throw error;
>        ^
>  
>  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/lib/index.js
>  require() of ES modules is not supported.
>  require() of /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/lib/index.js from /var/projects/27_09_2021ShcTest/functions/node_modules/svg2img/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
>  Instead rename /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/lib/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/package.json.
>  
>      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1152:13)
>      at Module.load (internal/modules/cjs/loader.js:984:32)
>      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
>      at Module.require (internal/modules/cjs/loader.js:1024:19)
>      at Module.require (pkg/prelude/bootstrap.js:1338:31)
>      at require (internal/modules/cjs/helpers.js:72:18)
>      at Object.<anonymous> (/var/projects/27_09_2021ShcTest/functions/node_modules/svg2img/index.js:1:13)
>      at Module._compile (internal/modules/cjs/loader.js:1136:30)
>      at Module._compile (pkg/prelude/bootstrap.js:1394:32)
>      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10) {
>    code: 'ERR_REQUIRE_ESM'
>  }
>  
>      at ChildProcess.exithandler (child_process.js:303:12)
>      at ChildProcess.emit (events.js:315:20)
>      at maybeClose (internal/child_process.js:1021:16)
>      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
>    killed: false,
>    code: 1,
>    signal: null,
>    cmd: '/usr/local/bin/firebase ./node_modules/health-cards-dev-tools/js/src/shc-validator.js --path  /var/projects/qrSDKDemo/health-cards-dev-tools/qrnumeric.txt --type qrnumeric',
>    stdout: '',
>    stderr: 'pkg/prelude/bootstrap.js:1359\n' +
>      '      throw error;\n' +
>      '      ^\n' +
>      '\n' +
>      'Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/lib/index.js\n' +
>      'require() of ES modules is not supported.\n' +
>      'require() of /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/lib/index.js from /var/projects/27_09_2021ShcTest/functions/node_modules/svg2img/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.\n' +
>      'Instead rename /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/lib/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /var/projects/27_09_2021ShcTest/functions/node_modules/canvg/package.json.\n' +
>      '\n' +
>      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1152:13)\n' +
>      '    at Module.load (internal/modules/cjs/loader.js:984:32)\n' +
>      '    at Function.Module._load (internal/modules/cjs/loader.js:877:14)\n' +
>      '    at Module.require (internal/modules/cjs/loader.js:1024:19)\n' +
>      '    at Module.require (pkg/prelude/bootstrap.js:1338:31)\n' +
>      '    at require (internal/modules/cjs/helpers.js:72:18)\n' +
>      '    at Object.<anonymous> (/var/projects/27_09_2021ShcTest/functions/node_modules/svg2img/index.js:1:13)\n' +
>      '    at Module._compile (internal/modules/cjs/loader.js:1136:30)\n' +
>      '    at Module._compile (pkg/prelude/bootstrap.js:1394:32)\n' +
>      '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10) {\n' +
>      "  code: 'ERR_REQUIRE_ESM'\n" +
>      '}\n'
>  }
========================

Environment Details:
OS - Linux Ubuntu 18.4
Node - v14.17.6

=========================
Package.json
  "dependencies": {
    "health-cards-dev-tools": "file:health-cards-dev-tools-1.0.2-0.tgz"
  },

**Comment by purushothaman-k** [comment] 2021-09-27 15:37
Got Same Issue
node: v14.17.6
npm: 6.14.15

ubuntu$  node ./node_modules/health-cards-dev-tools/js/src/shc-validator.js --path example.txt --type qrnumeric
internal/modules/cjs/loader.js:1089
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/vvdn/Desktop/C4/temp/node_modules/canvg/lib/index.js
require() of ES modules is not supported.
require() of /home/vvdn/Desktop/C4/temp/node_modules/canvg/lib/index.js from /home/vvdn/Desktop/C4/temp/node_modules/svg2img/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/vvdn/Desktop/C4/temp/node_modules/canvg/lib/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/vvdn/Desktop/C4/temp/node_modules/canvg/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/vvdn/Desktop/C4/temp/node_modules/svg2img/index.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by ljoy913** [comment] 2021-09-30 20:12
The cause of this problem is that `node_modules/canvg/package.json`  has `"type" : "module"` 
Changing it to `"type" : "commonjs"` fixes this issue.  I'm looking at finding a solution to this issue that does not require post-install hacking.

I'd like to reinforce that this is not a SMART QR Code validation module to be plugged into validation applications.  
From the README.md:

> NOTE: The goal of the project is to help implementers verify that their implementations conform to the specification. It optimistically tries to validate as much of the input artifacts as it can, continuing validation after encountering errors in order to give a complete validation report. It is therefore not meant to robustly validate actual SMART Health Cards; applications validating such cards must be thoroughly tested using an adversarial threat model.

**Comment by ljoy913** [comment] 2021-10-01 17:35
__canvg__ has committed a [fix ](https://github.com/canvg/canvg/commit/a9561b416f62e24c7e98435cf39ebbe1b8869520) to their master branch.  I verified these fixes will resolved this issue - once their npm package gets updated with these changes (presumably version 3.0.9)

**Comment by ljoy913** [comment] 2022-02-08 22:21
__canvg__ is no longer a dependency of this project.  Closing.

**Closed by ljoy913** 2022-02-08 22:21 UTC
